### ISSUE TITLE
k8s-to-oscal demo

### ISSUE THREAD

**Issue by AdrianHammond** [IBM/compliance-trestle-demos#24]
In the [k8s-to-oscal demo readme](https://github.com/IBM/compliance-trestle-demos/tree/develop/trestle_k8s#k8s-to-oscal) the spreadsheet link showing the mapping from YAML to OSCAL is broken.

**Comment by degenaro** [comment]
Thx. This is demo is actually obsolete. See of https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report/oscal-transformer for the current version.

TBD is to remove the demo from here.

**Comment by degenaro** [comment]
Corrections for this issue have been delivered to the `develop` branch.
